### ISSUE TITLE
[not an issue]  table prefix ?

### ISSUE THREAD

**Issue by raph-tr** [davidberriman/form_registration#2]
hi, i m very new to github, and not sure how to ask a question / request a feature... this may not be the correct way.. sorry
i was wondering if your code makes it possible to use prefixes on the db tables and if not how to modifiy it ? not sure i m able to make a pull request myself :)
regards.

**Comment by davidberriman** [comment]
Hi, 

I'm not sure I understand exactly what you mean, can you please give me some examples of what you're trying to achieve and I'll do my best to help? 

Regards
Dave

**Comment by raph-tr** [comment]
yep, sorry i was unclear, i was wondering if i could setup some prefixes for the db table, for instance having the tables beeing named "mysite_users_login, mysite_users_failed_logins, mysite_users_errorLogs" .
the question is : is there a simple way i can edit the code so the db queries can match these names ?
thx for your help :)

**Comment by davidberriman** [comment]
The easiest way is prob to use a good text editor that can do a find and replace. Textmate is a good example, when you go to the find option you can chose to replace the text with what you want. There is also an option to find and replace in a project rather than a document and if you select the top level folder it will replace each instance of it in all of the files. You need to be careful though that it doesn't replace something that wasn't a table name which could break something. It gives a list if each instance it finds and the file it found it in. It is well worth checking each item in the list to ensure they are all table names. 

Hope that helps

**Comment by davidberriman** [comment]
Hi,

I'm sorry, I was on my phone when I replied so hadn't checked the code in my project.

It is easy enough to change the table names in this project. You need to change the table names in the sql.txt file and then just change the $table_name variable at the top of each of the table classes to match those that you used in the sql.txt.

That should do the job.

Thanks
Dave

**Comment by raph-tr** [comment]
thx !! worked just fine :) :+1:
